apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: grizzly_alerts
    namespace: first_rules
spec:
    rules:
        - alert: PromScrapeFailed
          annotations:
            message: Prometheus failed to scrape a target {{ $labels.job }}  / {{ $labels.instance }}
          expr: up != 1
          for: 1m
          labels:
            severity: critical
        - expr: sum by(job) (up)
          record: job:up:sum
